name: S3 synchronization
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # sync a directory to an S3 bucket
      # 1) Sync dags/
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: 'mwaa-project-s3-prod'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-2'
          SOURCE_DIR: dags
          DEST_DIR: 'dags'
          
      # 2) Upload requirements.txt (single file)
      - name: Upload requirements.txt to S3
        run: |
          aws s3 cp requirements.txt s3://mwaa-project-s3-prod/requirements.txt
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2